// -----------------------------------------------------------------------------
// These options let you control Jest's behavior
// https://facebook.github.io/jest/docs/en/configuration.html
// -----------------------------------------------------------------------------
module.exports = {
  // automock [boolean]
  // browser [boolean]
  // bail [boolean]
  // cacheDirectory [string]
  // collectCoverage [boolean]
  // collectCoverageFrom [array]
  // coverageDirectory [string]
  // coveragePathIgnorePatterns [array<string>]
  // coverageReporters [array<string>]
  // coverageThreshold [object]
  // globals [object]
  // mapCoverage [boolean]
  // moduleFileExtensions [array<string>]
  // moduleDirectories [array<string>]
  // moduleNameMapper [object<string, string>]
  // modulePathIgnorePatterns [array<string>]
  // modulePaths [array<string>]
  // notify [boolean]
  // preset [string]
  // projects [array<string>]
  // clearMocks [boolean]
  // reporters [array<moduleName | [moduleName, options]>]
  // resetMocks [boolean]
  // resetModules [boolean]
  // resolver [string]
  // rootDir [string]
  // roots [array<string>]
  // setupFiles [array]
  // setupTestFrameworkScriptFile [string]
  // snapshotSerializers [array<string>]
  // testEnvironment [string]
  // testMatch [array<string>]
  // testPathIgnorePatterns [array<string>]
  // testRegex [string]
  // testResultsProcessor [string]
  // testRunner [string]
  // testURL [string]
  // timers [string]
  // transform [object<string, string>]
  // transformIgnorePatterns [array<string>]
  // unmockedModulePathPatterns [array<string>]
  // verbose [boolean]
}
